import { Conversation, Agent, Message } from './sample-data';

// Industry-specific demo data for 4 industries:
// 1. Healthcare
// 2. E-commerce/Retail
// 3. Financial Services/Banking
// 4. SaaS/Tech Support

// ============================================================================
// HEALTHCARE INDUSTRY DEMO DATA
// ============================================================================

export const healthcareConversations: Conversation[] = [
  {
    id: "health-001",
    customer: {
      id: "cust-health-001",
      name: "Robert Martinez",
      email: "robert.m@healthcare.com",
      phone: "+1 (555) 111-2222",
      avatar: "/professional-man-marcus.jpg",
      language: "English",
      preferredLanguage: "en",
      tier: "premium",
    },
    channel: "voice",
    status: "active",
    priority: "urgent",
    sentiment: "negative",
    sentimentScore: 0.22,
    sla: {
      deadline: new Date(Date.now() + 2 * 60 * 1000),
      remaining: 2,
      status: "warning",
    },
    assignedTo: "agent-health-001",
    queue: "Urgent Care",
    topic: "Appointment Scheduling - Urgent",
    lastMessage: "I need to see a doctor today, my symptoms are getting worse!",
    lastMessageTime: new Date(Date.now() - 1 * 60 * 1000),
    startTime: new Date(Date.now() - 5 * 60 * 1000),
    aiConfidence: 0.78,
    escalationRisk: true,
    tags: ["urgent", "appointment", "symptoms"],
    messages: [
      {
        id: "msg-health-001",
        type: "system",
        content: "Call connected - Urgent Care Queue",
        timestamp: new Date(Date.now() - 5 * 60 * 1000),
      },
      {
        id: "msg-health-002",
        type: "customer",
        content: "Hello, I need to schedule an urgent appointment. I've been experiencing severe chest pain and shortness of breath.",
        timestamp: new Date(Date.now() - 4 * 60 * 1000),
        sentiment: "negative",
        isTranscript: true,
      },
      {
        id: "msg-health-003",
        type: "ai",
        content: "I understand this is urgent. For chest pain and breathing difficulties, I'm connecting you immediately with our urgent care team. Please hold while I transfer you.",
        timestamp: new Date(Date.now() - 3 * 60 * 1000),
        confidence: 0.92,
        isTranscript: true,
      },
      {
        id: "msg-health-004",
        type: "customer",
        content: "I need to see a doctor today, my symptoms are getting worse!",
        timestamp: new Date(Date.now() - 1 * 60 * 1000),
        sentiment: "negative",
        isTranscript: true,
      },
    ],
  },
  {
    id: "health-002",
    customer: {
      id: "cust-health-002",
      name: "Patricia Chen",
      email: "patricia.c@email.com",
      phone: "+1 (555) 222-3333",
      avatar: "/professional-woman-emily.jpg",
      language: "English",
      preferredLanguage: "en",
      tier: "standard",
    },
    channel: "whatsapp",
    status: "active",
    priority: "medium",
    sentiment: "neutral",
    sentimentScore: 0.58,
    sla: {
      deadline: new Date(Date.now() + 30 * 60 * 1000),
      remaining: 30,
      status: "healthy",
    },
    assignedTo: "agent-health-002",
    queue: "Appointments",
    topic: "Prescription Refill",
    lastMessage: "Thank you! I'll pick it up at the pharmacy tomorrow.",
    lastMessageTime: new Date(Date.now() - 3 * 60 * 1000),
    startTime: new Date(Date.now() - 15 * 60 * 1000),
    aiConfidence: 0.95,
    escalationRisk: false,
    tags: ["prescription", "refill", "pharmacy"],
    messages: [
      {
        id: "msg-health-005",
        type: "system",
        content: "WhatsApp conversation started",
        timestamp: new Date(Date.now() - 15 * 60 * 1000),
      },
      {
        id: "msg-health-006",
        type: "customer",
        content: "Hi, I need to refill my prescription for blood pressure medication.",
        timestamp: new Date(Date.now() - 14 * 60 * 1000),
        sentiment: "neutral",
      },
      {
        id: "msg-health-007",
        type: "ai",
        content: "Hello Patricia! I can help with your prescription refill. Can you provide your patient ID or date of birth for verification?",
        timestamp: new Date(Date.now() - 13 * 60 * 1000),
        confidence: 0.96,
      },
      {
        id: "msg-health-008",
        type: "customer",
        content: "My patient ID is HC-789456. The medication is Lisinopril 10mg.",
        timestamp: new Date(Date.now() - 10 * 60 * 1000),
        sentiment: "neutral",
      },
      {
        id: "msg-health-009",
        type: "agent",
        content: "Perfect! I've processed your refill request. Your prescription will be ready for pickup at your preferred pharmacy tomorrow morning.",
        timestamp: new Date(Date.now() - 5 * 60 * 1000),
      },
      {
        id: "msg-health-010",
        type: "customer",
        content: "Thank you! I'll pick it up at the pharmacy tomorrow.",
        timestamp: new Date(Date.now() - 3 * 60 * 1000),
        sentiment: "positive",
      },
    ],
  },
  {
    id: "health-003",
    customer: {
      id: "cust-health-003",
      name: "Dr. Michael Thompson",
      email: "m.thompson@hospital.org",
      phone: "+1 (555) 333-4444",
      avatar: "/professional-man-david-agent.jpg",
      language: "English",
      preferredLanguage: "en",
      tier: "enterprise",
    },
    channel: "email",
    status: "active",
    priority: "high",
    sentiment: "neutral",
    sentimentScore: 0.52,
    sla: {
      deadline: new Date(Date.now() + 15 * 60 * 1000),
      remaining: 15,
      status: "healthy",
    },
    assignedTo: "agent-health-001",
    queue: "Medical Records",
    topic: "Medical Records Request",
    lastMessage: "I need patient records for John Doe, DOB 05/15/1980, for a consultation scheduled next week.",
    lastMessageTime: new Date(Date.now() - 20 * 60 * 1000),
    startTime: new Date(Date.now() - 45 * 60 * 1000),
    aiConfidence: 0.88,
    escalationRisk: false,
    tags: ["records", "hipaa", "enterprise"],
    messages: [
      {
        id: "msg-health-011",
        type: "system",
        content: "Email received from m.thompson@hospital.org",
        timestamp: new Date(Date.now() - 45 * 60 * 1000),
      },
      {
        id: "msg-health-012",
        type: "customer",
        content: "I need patient records for John Doe, DOB 05/15/1980, for a consultation scheduled next week. Please send via secure portal.",
        timestamp: new Date(Date.now() - 20 * 60 * 1000),
        sentiment: "neutral",
      },
    ],
  },
];

// ============================================================================
// E-COMMERCE/RETAIL INDUSTRY DEMO DATA
// ============================================================================

export const ecommerceConversations: Conversation[] = [
  {
    id: "ecom-001",
    customer: {
      id: "cust-ecom-001",
      name: "Lisa Anderson",
      email: "lisa.a@email.com",
      phone: "+1 (555) 444-5555",
      avatar: "/professional-woman-rachel.jpg",
      language: "English",
      preferredLanguage: "en",
      tier: "standard",
    },
    channel: "chat",
    status: "active",
    priority: "medium",
    sentiment: "negative",
    sentimentScore: 0.35,
    sla: {
      deadline: new Date(Date.now() + 20 * 60 * 1000),
      remaining: 20,
      status: "healthy",
    },
    assignedTo: "agent-ecom-001",
    queue: "Order Support",
    topic: "Order Not Delivered",
    lastMessage: "It's been 5 days and I still haven't received my order. This is unacceptable!",
    lastMessageTime: new Date(Date.now() - 2 * 60 * 1000),
    startTime: new Date(Date.now() - 10 * 60 * 1000),
    aiConfidence: 0.82,
    escalationRisk: true,
    tags: ["delivery", "order", "refund"],
    messages: [
      {
        id: "msg-ecom-001",
        type: "system",
        content: "Chat started via website widget",
        timestamp: new Date(Date.now() - 10 * 60 * 1000),
      },
      {
        id: "msg-ecom-002",
        type: "customer",
        content: "Hi, I placed an order #ORD-12345 last week and it hasn't arrived yet. Can you check the status?",
        timestamp: new Date(Date.now() - 9 * 60 * 1000),
        sentiment: "neutral",
      },
      {
        id: "msg-ecom-003",
        type: "ai",
        content: "Hello Lisa! I'd be happy to help you track your order. Let me check the status of order #ORD-12345 for you.",
        timestamp: new Date(Date.now() - 8 * 60 * 1000),
        confidence: 0.94,
      },
      {
        id: "msg-ecom-004",
        type: "customer",
        content: "It's been 5 days and I still haven't received my order. This is unacceptable!",
        timestamp: new Date(Date.now() - 2 * 60 * 1000),
        sentiment: "negative",
      },
    ],
  },
  {
    id: "ecom-002",
    customer: {
      id: "cust-ecom-002",
      name: "David Kim",
      email: "david.k@email.com",
      phone: "+1 (555) 555-6666",
      avatar: "/professional-asian-man-james.jpg",
      language: "English",
      preferredLanguage: "en",
      tier: "premium",
    },
    channel: "whatsapp",
    status: "active",
    priority: "low",
    sentiment: "positive",
    sentimentScore: 0.85,
    sla: {
      deadline: new Date(Date.now() + 45 * 60 * 1000),
      remaining: 45,
      status: "healthy",
    },
    assignedTo: "agent-ecom-002",
    queue: "Product Questions",
    topic: "Product Recommendation",
    lastMessage: "Perfect! I'll order the wireless headphones. Thanks for the recommendation!",
    lastMessageTime: new Date(Date.now() - 1 * 60 * 1000),
    startTime: new Date(Date.now() - 8 * 60 * 1000),
    aiConfidence: 0.91,
    escalationRisk: false,
    tags: ["product", "recommendation", "upsell"],
    messages: [
      {
        id: "msg-ecom-005",
        type: "system",
        content: "WhatsApp conversation started",
        timestamp: new Date(Date.now() - 8 * 60 * 1000),
      },
      {
        id: "msg-ecom-006",
        type: "customer",
        content: "Hi! I'm looking for wireless headphones under $200. What would you recommend?",
        timestamp: new Date(Date.now() - 7 * 60 * 1000),
        sentiment: "positive",
      },
      {
        id: "msg-ecom-007",
        type: "ai",
        content: "Hello David! Based on your budget, I'd recommend our Premium Wireless Headphones. They have excellent sound quality, 30-hour battery life, and are currently on sale for $179.99. Would you like more details?",
        timestamp: new Date(Date.now() - 6 * 60 * 1000),
        confidence: 0.93,
      },
      {
        id: "msg-ecom-008",
        type: "customer",
        content: "Perfect! I'll order the wireless headphones. Thanks for the recommendation!",
        timestamp: new Date(Date.now() - 1 * 60 * 1000),
        sentiment: "positive",
      },
    ],
  },
  {
    id: "ecom-003",
    customer: {
      id: "cust-ecom-003",
      name: "Sarah Williams",
      email: "sarah.w@email.com",
      phone: "+1 (555) 666-7777",
      avatar: "/professional-woman-sarah-agent.jpg",
      language: "English",
      preferredLanguage: "en",
      tier: "standard",
    },
    channel: "email",
    status: "active",
    priority: "medium",
    sentiment: "neutral",
    sentimentScore: 0.60,
    sla: {
      deadline: new Date(Date.now() + 25 * 60 * 1000),
      remaining: 25,
      status: "healthy",
    },
    assignedTo: null,
    queue: "Returns",
    topic: "Return Request",
    lastMessage: "I'd like to return item #PROD-789. It doesn't fit as expected. What's the return process?",
    lastMessageTime: new Date(Date.now() - 5 * 60 * 1000),
    startTime: new Date(Date.now() - 10 * 60 * 1000),
    aiConfidence: 0.89,
    escalationRisk: false,
    tags: ["return", "refund", "policy"],
    messages: [
      {
        id: "msg-ecom-009",
        type: "system",
        content: "Email received from sarah.w@email.com",
        timestamp: new Date(Date.now() - 10 * 60 * 1000),
      },
      {
        id: "msg-ecom-010",
        type: "customer",
        content: "I'd like to return item #PROD-789. It doesn't fit as expected. What's the return process?",
        timestamp: new Date(Date.now() - 5 * 60 * 1000),
        sentiment: "neutral",
      },
    ],
  },
];

// ============================================================================
// FINANCIAL SERVICES/BANKING INDUSTRY DEMO DATA
// ============================================================================

export const bankingConversations: Conversation[] = [
  {
    id: "bank-001",
    customer: {
      id: "cust-bank-001",
      name: "Jennifer Lopez",
      email: "j.lopez@email.com",
      phone: "+1 (555) 777-8888",
      avatar: "/professional-woman-maria-agent.jpg",
      language: "English",
      preferredLanguage: "en",
      tier: "premium",
    },
    channel: "voice",
    status: "active",
    priority: "urgent",
    sentiment: "negative",
    sentimentScore: 0.15,
    sla: {
      deadline: new Date(Date.now() + 1 * 60 * 1000),
      remaining: 1,
      status: "warning",
    },
    assignedTo: "agent-bank-001",
    queue: "Fraud Prevention",
    topic: "Suspicious Transaction",
    lastMessage: "I didn't make this $2,500 purchase! Please freeze my card immediately!",
    lastMessageTime: new Date(Date.now() - 30 * 1000),
    startTime: new Date(Date.now() - 3 * 60 * 1000),
    aiConfidence: 0.95,
    escalationRisk: true,
    tags: ["fraud", "urgent", "security"],
    messages: [
      {
        id: "msg-bank-001",
        type: "system",
        content: "Call connected - Fraud Prevention Queue (Priority)",
        timestamp: new Date(Date.now() - 3 * 60 * 1000),
      },
      {
        id: "msg-bank-002",
        type: "customer",
        content: "I just received an alert about a $2,500 charge I didn't make. I need to report fraud immediately!",
        timestamp: new Date(Date.now() - 2 * 60 * 1000),
        sentiment: "negative",
        isTranscript: true,
      },
      {
        id: "msg-bank-003",
        type: "ai",
        content: "I understand this is urgent. I'm immediately connecting you with our fraud prevention specialist. Your card will be frozen right away.",
        timestamp: new Date(Date.now() - 1 * 60 * 1000),
        confidence: 0.97,
        isTranscript: true,
      },
      {
        id: "msg-bank-004",
        type: "customer",
        content: "I didn't make this $2,500 purchase! Please freeze my card immediately!",
        timestamp: new Date(Date.now() - 30 * 1000),
        sentiment: "negative",
        isTranscript: true,
      },
    ],
  },
  {
    id: "bank-002",
    customer: {
      id: "cust-bank-002",
      name: "Thomas Brown",
      email: "thomas.b@email.com",
      phone: "+1 (555) 888-9999",
      avatar: "/professional-man-marcus.jpg",
      language: "English",
      preferredLanguage: "en",
      tier: "enterprise",
    },
    channel: "email",
    status: "active",
    priority: "high",
    sentiment: "neutral",
    sentimentScore: 0.55,
    sla: {
      deadline: new Date(Date.now() + 10 * 60 * 1000),
      remaining: 10,
      status: "healthy",
    },
    assignedTo: "agent-bank-002",
    queue: "Loan Services",
    topic: "Mortgage Application",
    lastMessage: "I've submitted all required documents. When can I expect a decision on my mortgage application?",
    lastMessageTime: new Date(Date.now() - 15 * 60 * 1000),
    startTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    aiConfidence: 0.87,
    escalationRisk: false,
    tags: ["loan", "mortgage", "application"],
    messages: [
      {
        id: "msg-bank-005",
        type: "system",
        content: "Email received from thomas.b@email.com",
        timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
      {
        id: "msg-bank-006",
        type: "customer",
        content: "I've submitted all required documents. When can I expect a decision on my mortgage application?",
        timestamp: new Date(Date.now() - 15 * 60 * 1000),
        sentiment: "neutral",
      },
    ],
  },
  {
    id: "bank-003",
    customer: {
      id: "cust-bank-003",
      name: "Amanda Taylor",
      email: "amanda.t@email.com",
      phone: "+1 (555) 999-0000",
      avatar: "/professional-woman-emily.jpg",
      language: "English",
      preferredLanguage: "en",
      tier: "premium",
    },
    channel: "chat",
    status: "active",
    priority: "medium",
    sentiment: "positive",
    sentimentScore: 0.75,
    sla: {
      deadline: new Date(Date.now() + 30 * 60 * 1000),
      remaining: 30,
      status: "healthy",
    },
    assignedTo: "agent-bank-001",
    queue: "Account Services",
    topic: "Account Balance Inquiry",
    lastMessage: "Thank you! That's exactly what I needed to know.",
    lastMessageTime: new Date(Date.now() - 2 * 60 * 1000),
    startTime: new Date(Date.now() - 8 * 60 * 1000),
    aiConfidence: 0.96,
    escalationRisk: false,
    tags: ["balance", "account", "inquiry"],
    messages: [
      {
        id: "msg-bank-007",
        type: "system",
        content: "Chat started via mobile app",
        timestamp: new Date(Date.now() - 8 * 60 * 1000),
      },
      {
        id: "msg-bank-008",
        type: "customer",
        content: "Hi, can you tell me my current account balance?",
        timestamp: new Date(Date.now() - 7 * 60 * 1000),
        sentiment: "neutral",
      },
      {
        id: "msg-bank-009",
        type: "ai",
        content: "Hello Amanda! For security, I'll need to verify your identity. Can you provide the last 4 digits of your account number?",
        timestamp: new Date(Date.now() - 6 * 60 * 1000),
        confidence: 0.94,
      },
      {
        id: "msg-bank-010",
        type: "customer",
        content: "Sure, it's 7890.",
        timestamp: new Date(Date.now() - 4 * 60 * 1000),
        sentiment: "neutral",
      },
      {
        id: "msg-bank-011",
        type: "agent",
        content: "Thank you! Your current balance is $12,456.78. Is there anything else I can help you with?",
        timestamp: new Date(Date.now() - 3 * 60 * 1000),
      },
      {
        id: "msg-bank-012",
        type: "customer",
        content: "Thank you! That's exactly what I needed to know.",
        timestamp: new Date(Date.now() - 2 * 60 * 1000),
        sentiment: "positive",
      },
    ],
  },
];

// ============================================================================
// SAAS/TECH SUPPORT INDUSTRY DEMO DATA
// ============================================================================

export const saasConversations: Conversation[] = [
  {
    id: "saas-001",
    customer: {
      id: "cust-saas-001",
      name: "Ryan Patel",
      email: "ryan.p@startup.io",
      phone: "+1 (555) 101-2020",
      avatar: "/professional-asian-man-james.jpg",
      language: "English",
      preferredLanguage: "en",
      tier: "enterprise",
    },
    channel: "chat",
    status: "active",
    priority: "high",
    sentiment: "negative",
    sentimentScore: 0.28,
    sla: {
      deadline: new Date(Date.now() + 5 * 60 * 1000),
      remaining: 5,
      status: "warning",
    },
    assignedTo: "agent-saas-001",
    queue: "Technical Support",
    topic: "API Integration Issue",
    lastMessage: "Our production API calls are failing with 500 errors. This is affecting our entire platform!",
    lastMessageTime: new Date(Date.now() - 1 * 60 * 1000),
    startTime: new Date(Date.now() - 20 * 60 * 1000),
    aiConfidence: 0.76,
    escalationRisk: true,
    tags: ["api", "integration", "production", "urgent"],
    messages: [
      {
        id: "msg-saas-001",
        type: "system",
        content: "Chat started via website widget",
        timestamp: new Date(Date.now() - 20 * 60 * 1000),
      },
      {
        id: "msg-saas-002",
        type: "customer",
        content: "Hi, we're experiencing API errors. Our integration is failing with 500 status codes.",
        timestamp: new Date(Date.now() - 19 * 60 * 1000),
        sentiment: "neutral",
      },
      {
        id: "msg-saas-003",
        type: "ai",
        content: "Hello Ryan! I understand you're experiencing API errors. Let me check our system status and gather some details. Can you share the API endpoint you're calling and any error messages?",
        timestamp: new Date(Date.now() - 18 * 60 * 1000),
        confidence: 0.91,
      },
      {
        id: "msg-saas-004",
        type: "customer",
        content: "We're calling /api/v2/users endpoint. The error says 'Internal Server Error'. This started about 30 minutes ago.",
        timestamp: new Date(Date.now() - 15 * 60 * 1000),
        sentiment: "negative",
      },
      {
        id: "msg-saas-005",
        type: "agent",
        content: "I see the issue. There's a known issue with our /api/v2/users endpoint affecting some enterprise accounts. Our engineering team is working on a fix. I can provide a workaround using /api/v1/users in the meantime.",
        timestamp: new Date(Date.now() - 10 * 60 * 1000),
      },
      {
        id: "msg-saas-006",
        type: "customer",
        content: "Our production API calls are failing with 500 errors. This is affecting our entire platform!",
        timestamp: new Date(Date.now() - 1 * 60 * 1000),
        sentiment: "negative",
      },
    ],
  },
  {
    id: "saas-002",
    customer: {
      id: "cust-saas-002",
      name: "Emma Wilson",
      email: "emma.w@company.com",
      phone: "+1 (555) 202-3030",
      avatar: "/professional-woman-rachel.jpg",
      language: "English",
      preferredLanguage: "en",
      tier: "premium",
    },
    channel: "email",
    status: "active",
    priority: "medium",
    sentiment: "positive",
    sentimentScore: 0.82,
    sla: {
      deadline: new Date(Date.now() + 25 * 60 * 1000),
      remaining: 25,
      status: "healthy",
    },
    assignedTo: "agent-saas-002",
    queue: "Onboarding",
    topic: "Account Setup",
    lastMessage: "Thanks for the detailed guide! I've successfully set up our team workspace.",
    lastMessageTime: new Date(Date.now() - 10 * 60 * 1000),
    startTime: new Date(Date.now() - 2 * 60 * 60 * 1000),
    aiConfidence: 0.93,
    escalationRisk: false,
    tags: ["onboarding", "setup", "workspace"],
    messages: [
      {
        id: "msg-saas-007",
        type: "system",
        content: "Email received from emma.w@company.com",
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
      {
        id: "msg-saas-008",
        type: "customer",
        content: "Hi, I'm new to the platform and need help setting up our team workspace. Can you provide guidance?",
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
        sentiment: "neutral",
      },
      {
        id: "msg-saas-009",
        type: "agent",
        content: "Hello Emma! Welcome to our platform. I've sent you a comprehensive setup guide via email. It includes step-by-step instructions for creating your workspace, inviting team members, and configuring your first project.",
        timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
      },
      {
        id: "msg-saas-010",
        type: "customer",
        content: "Thanks for the detailed guide! I've successfully set up our team workspace.",
        timestamp: new Date(Date.now() - 10 * 60 * 1000),
        sentiment: "positive",
      },
    ],
  },
  {
    id: "saas-003",
    customer: {
      id: "cust-saas-003",
      name: "Daniel Lee",
      email: "daniel.l@tech.com",
      phone: "+1 (555) 303-4040",
      avatar: "/professional-man-david-agent.jpg",
      language: "English",
      preferredLanguage: "en",
      tier: "standard",
    },
    channel: "whatsapp",
    status: "active",
    priority: "low",
    sentiment: "neutral",
    sentimentScore: 0.65,
    sla: {
      deadline: new Date(Date.now() + 40 * 60 * 1000),
      remaining: 40,
      status: "healthy",
    },
    assignedTo: null,
    queue: "Feature Questions",
    topic: "Feature Request",
    lastMessage: "That would be amazing! When can we expect this feature?",
    lastMessageTime: new Date(Date.now() - 5 * 60 * 1000),
    startTime: new Date(Date.now() - 12 * 60 * 1000),
    aiConfidence: 0.88,
    escalationRisk: false,
    tags: ["feature", "request", "roadmap"],
    messages: [
      {
        id: "msg-saas-011",
        type: "system",
        content: "WhatsApp conversation started",
        timestamp: new Date(Date.now() - 12 * 60 * 1000),
      },
      {
        id: "msg-saas-012",
        type: "customer",
        content: "Hi! I was wondering if you have plans to add dark mode to the dashboard?",
        timestamp: new Date(Date.now() - 11 * 60 * 1000),
        sentiment: "neutral",
      },
      {
        id: "msg-saas-013",
        type: "ai",
        content: "Hello Daniel! Great question. Dark mode is actually on our roadmap for Q2. I can add you to our beta testing list if you're interested in early access!",
        timestamp: new Date(Date.now() - 10 * 60 * 1000),
        confidence: 0.90,
      },
      {
        id: "msg-saas-014",
        type: "customer",
        content: "That would be amazing! When can we expect this feature?",
        timestamp: new Date(Date.now() - 5 * 60 * 1000),
        sentiment: "positive",
      },
    ],
  },
];

// ============================================================================
// COMBINED INDUSTRY DEMO DATA
// ============================================================================

export const allIndustryConversations: Conversation[] = [
  ...healthcareConversations,
  ...ecommerceConversations,
  ...bankingConversations,
  ...saasConversations,
];

// Industry-specific agents
export const industryAgents: Agent[] = [
  // Healthcare agents
  {
    id: "agent-health-001",
    name: "Dr. Sarah Mitchell",
    email: "sarah.m@healthcare.com",
    avatar: "/professional-woman-sarah-agent.jpg",
    status: "online",
    role: "agent",
    activeConversations: 3,
    avgHandleTime: 12.5,
    csat: 4.9,
  },
  {
    id: "agent-health-002",
    name: "Michael Chen",
    email: "michael.c@healthcare.com",
    avatar: "/professional-man-david-agent.jpg",
    status: "busy",
    role: "agent",
    activeConversations: 4,
    avgHandleTime: 10.2,
    csat: 4.7,
  },
  // E-commerce agents
  {
    id: "agent-ecom-001",
    name: "Jessica Martinez",
    email: "jessica.m@ecommerce.com",
    avatar: "/professional-woman-maria-agent.jpg",
    status: "online",
    role: "agent",
    activeConversations: 5,
    avgHandleTime: 6.8,
    csat: 4.6,
  },
  {
    id: "agent-ecom-002",
    name: "Alex Johnson",
    email: "alex.j@ecommerce.com",
    avatar: "/professional-person-alex-agent.jpg",
    status: "online",
    role: "agent",
    activeConversations: 3,
    avgHandleTime: 7.5,
    csat: 4.8,
  },
  // Banking agents
  {
    id: "agent-bank-001",
    name: "Robert Williams",
    email: "robert.w@banking.com",
    avatar: "/professional-man-marcus.jpg",
    status: "busy",
    role: "supervisor",
    activeConversations: 2,
    avgHandleTime: 15.3,
    csat: 4.9,
  },
  {
    id: "agent-bank-002",
    name: "Patricia Davis",
    email: "patricia.d@banking.com",
    avatar: "/professional-woman-emily.jpg",
    status: "online",
    role: "agent",
    activeConversations: 4,
    avgHandleTime: 11.2,
    csat: 4.7,
  },
  // SaaS agents
  {
    id: "agent-saas-001",
    name: "David Kim",
    email: "david.k@saas.com",
    avatar: "/professional-asian-man-james.jpg",
    status: "online",
    role: "agent",
    activeConversations: 3,
    avgHandleTime: 18.5,
    csat: 4.8,
  },
  {
    id: "agent-saas-002",
    name: "Emily Rodriguez",
    email: "emily.r@saas.com",
    avatar: "/professional-woman-rachel.jpg",
    status: "online",
    role: "agent",
    activeConversations: 2,
    avgHandleTime: 16.2,
    csat: 4.9,
  },
];



